gwp/routes/web.php
<?php

use App\Http\Controllers\DealController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [FrontendController::class, 'index'])->name('welcome');
Route::get('/', [FrontendController::class, 'home'])->name('home');
Route::get('/register-form', [FrontendController::class, 'studentpdf'])->name('student.pdf');
Route::get('/employment-form', [FrontendController::class, 'teacherpdf'])->name('teacher.pdf');





Route::get('/dashboard/admin', function () {
    return view('backend.admin.index');
})->middleware(['auth'])->name('dashboard.admin');

    Route::resource('teachers', TeacherController::class);
    Route::resource('staffs', StaffController::class);
    Route::resource('schedules', ScheduleController::class);

Route::get('/dashboard/principal', function () {
    return view('backend.principal.index');
})->middleware(['auth'])->name('dashboard.principal');

    Route::resource('deals', DealController::class);
    Route::get('/dashboard/principal/schedule', [PrincipalController::class, 'schedule'])->name('principal.schedule');




Route::get('/dashboard/parent', function () {
    return view('backend.parent.index');
})->middleware(['auth'])->name('dashboard.parent');



Route::get('/dashboard/teacher', function () {
    return view('backend.teacher.index');
})->middleware(['auth'])->name('dashboard.teacher');

    Route::resource('teachers', TeacherController::class);
    Route::get('/dashboard/teacher/schedule', [TeacherController::class, 'schedule'])->name('teacher.schedule');
    Route::get('/dashboard/teacher/croutine', [TeacherController::class, 'routine'])->name('teachers.routine');


Route::get('/dashboard/student', function () {
    return view('backend.student.index');
})->middleware(['auth'])->name('dashboard.student');

    Route::resource('students', StudentController::class);
    Route::get('/dashboard/student/schedule', [StudentController::class, 'schedule'])->name('student.schedule');
    Route::get('/dashboard/student/croutine', [StudentController::class, 'routine'])->name('students.routine');

require __DIR__.'/auth.php';

gwp/resources/views/backend/admin/staff-crud/create.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Staffs</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Staffs</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Register New Staff
                                <a class="btn btn-sm btn-primary" href="{{ route('staffs.index')}}"> Staff List</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('staffs.store')}}" method="POST">
    @csrf
                
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name')}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="contact" class="form-label">Contact</label>
                    <input name="contact" type="number" class="form-control" id="contact" value="{{old('number')}}" >
                    
                    @error('contact')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="email" value="{{old('email')}}" >
                    
                    @error('email')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="present_address" class="form-label">Present Address</label>
                    <input name="present_address" type="varchar" class="form-control" id="present_address" value="{{old('present_address')}}" >
                    
                    @error('present_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="permanent_address" class="form-label">Permanent Address </label>
                    <input name="permanent_address" type="varchar" class="form-control" id="permanent_address" value="{{old('permanent_address')}}" >
                    
                    @error('permanent_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="designation" class="form-label">Designation</label>
                    <input name="designation" type="text" class="form-control" id="designation" value="{{old('designation')}}" >
                    
                    @error('designation')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="educational_qualification" class="form-label">Educational Qualification</label>
                    <input name="educational_qualification" type="text" class="form-control" id="educational_qualification" value="{{old('educational_qualification')}}" >
                    
                    @error('educational_qualification')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="joining_date" class="form-label">Joining Date</label>
                    <input name="joining_date" type="date" class="form-control" id="joining_date" value="{{old('joining_date')}}" >
                    
                    @error('joining_date')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
                   
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/staff-crud/edit.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">{{ $staff->name }}</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                            <li class="breadcrumb-item active">staffs</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Edit Staff Information
                                <a class="btn btn-sm btn-primary" href="{{ route('staffs.index')}}"> Staff List</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('staffs.update', ['staff' => $staff->id])}}" method="POST">
    @csrf
      @method('PATCH')          

                


                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name', $staff->name)}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="contact" class="form-label">Contact</label>
                    <input name="contact" type="number" class="form-control" id="contact" value="{{old('number', $staff->contact)}}" >
                    
                    @error('contact')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="email" value="{{old('email', $staff->email)}}" >
                    
                    @error('email')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="present_address" class="form-label">Present Address</label>
                    <input name="present_address" type="varchar" class="form-control" id="present_address" value="{{old('present_address', $staff->present_address)}}" >
                    
                    @error('present_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="permanent_address" class="form-label">Permanent Address </label>
                    <input name="permanent_address" type="varchar" class="form-control" id="permanent_address" value="{{old('permanent_address', $staff->permanent_address)}}" >
                    
                    @error('permanent_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="designation" class="form-label">Designation</label>
                    <input name="designation" type="text" class="form-control" id="designation" value="{{old('designation', $staff->designation)}}" >
                    
                    @error('designation')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="educational_qualification" class="form-label">Educational Qualification</label>
                    <input name="educational_qualification" type="text" class="form-control" id="educational_qualification" value="{{old('educational_qualification', $staff->educational_qualification)}}" >
                    
                    @error('educational_qualification')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="joining_date" class="form-label">Joining Date</label>
                    <input name="joining_date" type="date" class="form-control" id="joining_date" value="{{old('joining_date', $staff->joining_date)}}" >
                    
                    @error('joining_date')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
                   
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/staff-crud/index.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Staffs</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">staffs</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Staff List
                                <a class="btn btn-sm btn-primary" href="{{ route('staffs.create')}}">Register New Staff </a>
                            </div>
                            <div class="card-body">
                                @if(session('message'))
                                <p class="alert alert-success">{{ session('message') }}</p>
                                @endif
                                <div class="col-md-12">
                                <table id="datatablesSimple" style="width: 100%">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Designation</th>
                                            <th>Contact </th>
                                            <th>Email</th>
                                            <!-- <th>Present Address</th>
                                            <th>Permanent Address</th> -->

                                            <!-- <th>Educational Qualification</th>
                                            <th>Joining Date</th> -->
        
                                            <th>Action</th>
                                          
                                        </tr>
                                    </thead>
                                    
    <tbody>
        @foreach ($staffs as $staff)
        <tr>
            <td>{{ $loop->iteration }}</td>
            
            <td>{{ $staff->name }} </td>
             <td>{{ $staff->designation }} </td>
            <td>{{ $staff->contact }} </td>
            <td>{{ $staff->email }} </td>
            
            <td>
            <a class="btn btn-warning btn-sm" href="{{route('staffs.show', ['staff' => $staff->id]) }}"> Show </a>
                
                <a class="btn btn-warning btn-sm" href="{{route('staffs.edit', ['staff' => $staff->id]) }}"> Edit </a>
                
                <form action="{{ route('staffs.destroy', ['staff' => $staff->id]) }}" method="POST" style="display:inline">
                   @csrf
                   @method('delete') 
                   <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
                </form>
               
            
            </td>
            
        </tr>
        @endforeach
    </tbody>
</table>
</div>
                            </div>
                        </div>
                    </div>
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/staff-crud/show.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Staffs</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Staffs</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Staff Details
                                <a class="btn btn-sm btn-primary" href="{{ route('staffs.index')}}">Staff List </a>
                            </div>
                            <div class="card-body">

                               
                               <h3> Name: {{$staff->name}}</h3>
                               
                                <p> Contact: {{ $staff->contact }} </p>
                               <p> Email: {{ $staff->email }} </p>
                               <p> Present Address: {{ $staff->present_address }} </p>
                               <p> Permanent Address: {{ $staff->permanent_address }} </p>
                               <p> Designation: {{ $staff->designation }} </p>
                               <p> Educational Qualification: {{ $staff->educational_qualification }} </p>
                               <p> Joining Date: {{ $staff->joining_date }} </p>
                              
                            </div>
                        </div>
                    </div>
</x-backend.admin.layouts.master>