gwp/routes/web.php
<?php

use App\Http\Controllers\DealController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [FrontendController::class, 'index'])->name('welcome');
Route::get('/', [FrontendController::class, 'home'])->name('home');
Route::get('/register-form', [FrontendController::class, 'studentpdf'])->name('student.pdf');
Route::get('/employment-form', [FrontendController::class, 'teacherpdf'])->name('teacher.pdf');





Route::get('/dashboard/admin', function () {
    return view('backend.admin.index');
})->middleware(['auth'])->name('dashboard.admin');

    Route::resource('teachers', TeacherController::class);
    Route::resource('staffs', StaffController::class);
    Route::resource('schedules', ScheduleController::class);

Route::get('/dashboard/principal', function () {
    return view('backend.principal.index');
})->middleware(['auth'])->name('dashboard.principal');

    Route::resource('deals', DealController::class);
    Route::get('/dashboard/principal/schedule', [PrincipalController::class, 'schedule'])->name('principal.schedule');




Route::get('/dashboard/parent', function () {
    return view('backend.parent.index');
})->middleware(['auth'])->name('dashboard.parent');



Route::get('/dashboard/teacher', function () {
    return view('backend.teacher.index');
})->middleware(['auth'])->name('dashboard.teacher');

    Route::resource('teachers', TeacherController::class);
    Route::get('/dashboard/teacher/schedule', [TeacherController::class, 'schedule'])->name('teacher.schedule');
    Route::get('/dashboard/teacher/croutine', [TeacherController::class, 'routine'])->name('teachers.routine');


Route::get('/dashboard/student', function () {
    return view('backend.student.index');
})->middleware(['auth'])->name('dashboard.student');

    Route::resource('students', StudentController::class);
    Route::get('/dashboard/student/schedule', [StudentController::class, 'schedule'])->name('student.schedule');
    Route::get('/dashboard/student/croutine', [StudentController::class, 'routine'])->name('students.routine');

require __DIR__.'/auth.php';

gwp/app/Models/Deal.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Deal extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'amount', 'dealtype'];
}

gwp/app/Http/Controllers/DealController.php
<?php

namespace App\Http\Controllers;

use App\Models\Deal;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class DealController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $deals = Deal::all();
        return view('backend.principal.deals.index', compact('deals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.principal.deals.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try
        {
            Deal::create($request->all());   
 
            return redirect()->route('deals.index')->withMessage('Successfully Saved !');

        }
        catch(QueryException $e)
        {
             return redirect()->back()->withInput()->withErrors($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Deal $deal)
    {
        return view('backend.principal.deals.edit', compact('deal'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Deal $deal)
    {
        try
        { 
            
            $deal->update([
                'name' => $request->name,
                'amount' => $request->amount,
                'dealtype' => $request->dealtype
            ]);

            return redirect()->route('deals.index')->withMessage('Successfully Updated!');
       }
       catch (QueryException $e)
       {
           return redirect()->back()->withInput()->withErrors($e->getMessage());
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Deal $deal)
    {
        $deal->delete();
        return redirect()->route('schedules.index')->withMessage('Successfully Deleted !');
    }
}

gwp/app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Schedule;
use Illuminate\Http\Request;

class PrincipalController extends Controller
{
    public function schedule()
    {
        $schedules = Schedule::all();
        return view('backend.principal.schedule', compact('schedules'));
    }
}

gwp/resources/views/backend/principal/deals/create.blade.php
<x-backend.principal.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Earnings & Expense</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Earnings & Expense</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Register New Event
                                <a class="btn btn-sm btn-primary" href="{{ route('deals.index')}}"> Business Records</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('deals.store')}}" method="POST">
    @csrf
                
                <div class="mb-3">
                    <label for="name" class="form-label">Transactions</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name')}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="amount" class="form-label">Amount</label>
                    <input name="amount" type="number" class="form-control" id="amount" value="{{old('amount')}}" >
                    
                    @error('amount')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="dealtype" class="form-label">Deal Type</label>
                    <select name="dealtype" type="text" class="form-control" id="dealtype">
                        <option value="{{'Earnings'}}">Earnings</option>
                        <option value="{{'Expense'}}">Expense</option>
                    </select>
                    
                    @error('dealtype')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
</x-backend.principal.layouts.master>

gwp/resources/views/backend/principal/deals/edit.blade.php
<x-backend.principal.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Edit Transaction</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                            <li class="breadcrumb-item active">Transaction</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Edit Earnings & Expense
                                <a class="btn btn-sm btn-primary" href="{{ route('schedules.index')}}"> Transactions</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('deals.update', ['deal' => $deal->id])}}" method="POST">
    @csrf
      @method('PATCH')          

                <div class="mb-3">
                    <label for="name" class="form-label">Transactions</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name', $deal->name)}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="amount" class="form-label">Amount</label>
                    <input name="amount" type="number" class="form-control" id="amount" value="{{old('amount', $deal->amount)}}" >
                    
                    @error('amount')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="dealtype" class="form-label">Deal Type</label>
                    <select name="dealtype" type="text" class="form-control" id="dealtype">
                        <option value="{{'Earnings'}}">Earnings</option>
                        <option value="{{'Expense'}}">Expense</option>
                    </select>  
                    
                    @error('dealtype')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
                   
</x-backend.principal.layouts.master>

gwp/resources/views/backend/principal/deals/index.blade.php
<x-backend.principal.layouts.master>
<div class="container-fluid px-4">
    <h1 class="mt-4">Earnings & Expense</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Earnings & Expense</li>
    </ol>
    
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Events
            <a class="btn btn-sm btn-primary" href="{{ route('deals.create')}}">Register New Transaction </a>
        </div>
        <div class="card-body">
            @if(session('message'))
            <p class="alert alert-success">{{ session('message') }}</p>
            @endif
            <div class="col-md-12">
            <table id="datatablesSimple" style="width: 100%">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Transactions</th>
                        <th>Amount</th>
                        <th>Deal Type</th>
                        <th>Action</th>
                        
                    </tr>
                </thead>
                
                <tbody>
                    @foreach ($deals as $deal)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $deal->name }} </td>
                        <td>{{ $deal->amount }} </td>
                        <td>{{ $deal->dealtype }} </td>
                        
                        
                        <td>
                            <a class="btn btn-warning btn-sm" href="{{route('deals.edit', ['deal' => $deal->id]) }}"> Edit </a>
                            
                            <form action="{{ route('deals.destroy', ['deal' => $deal->id]) }}" method="POST" style="display:inline">
                            @csrf
                            @method('delete') 
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
                            </form>
                        </td>
                        
                    </tr>
                    @endforeach
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
</x-backend.principal.layouts.master>