gwp/routes/web.php
<?php

use App\Http\Controllers\DealController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [FrontendController::class, 'index'])->name('welcome');
Route::get('/', [FrontendController::class, 'home'])->name('home');
Route::get('/register-form', [FrontendController::class, 'studentpdf'])->name('student.pdf');
Route::get('/employment-form', [FrontendController::class, 'teacherpdf'])->name('teacher.pdf');





Route::get('/dashboard/admin', function () {
    return view('backend.admin.index');
})->middleware(['auth'])->name('dashboard.admin');

    Route::resource('teachers', TeacherController::class);
    Route::resource('staffs', StaffController::class);
    Route::resource('schedules', ScheduleController::class);

Route::get('/dashboard/principal', function () {
    return view('backend.principal.index');
})->middleware(['auth'])->name('dashboard.principal');

    Route::resource('deals', DealController::class);
    Route::get('/dashboard/principal/schedule', [PrincipalController::class, 'schedule'])->name('principal.schedule');




Route::get('/dashboard/parent', function () {
    return view('backend.parent.index');
})->middleware(['auth'])->name('dashboard.parent');



Route::get('/dashboard/teacher', function () {
    return view('backend.teacher.index');
})->middleware(['auth'])->name('dashboard.teacher');

    Route::resource('teachers', TeacherController::class);
    Route::get('/dashboard/teacher/schedule', [TeacherController::class, 'schedule'])->name('teacher.schedule');
    Route::get('/dashboard/teacher/croutine', [TeacherController::class, 'routine'])->name('teachers.routine');


Route::get('/dashboard/student', function () {
    return view('backend.student.index');
})->middleware(['auth'])->name('dashboard.student');

    Route::resource('students', StudentController::class);
    Route::get('/dashboard/student/schedule', [StudentController::class, 'schedule'])->name('student.schedule');
    Route::get('/dashboard/student/croutine', [StudentController::class, 'routine'])->name('students.routine');

require __DIR__.'/auth.php';

gwp/resources/views/backend/admin/teacher-crud/create.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Teachers</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">teachers</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Register New Teacher
                                <a class="btn btn-sm btn-primary" href="{{ route('teachers.index')}}"> Teacher List</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('teachers.store')}}" method="POST">
    @csrf
                

                <div class="mb-3">
                    <label for="title" class="form-label">Subject</label>
                    <input name="subject" type="text" class="form-control" id="subject" value="{{old('subject')}}">
                    
                    @error('subject')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>


                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name')}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="contact" class="form-label">Contact</label>
                    <input name="contact" type="number" class="form-control" id="contact" value="{{old('number')}}" >
                    
                    @error('contact')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="email" value="{{old('email')}}" >
                    
                    @error('email')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="present_address" class="form-label">Present Address</label>
                    <input name="present_address" type="varchar" class="form-control" id="present_address" value="{{old('present_address')}}" >
                    
                    @error('present_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="permanent_address" class="form-label">Permanent Address </label>
                    <input name="permanent_address" type="varchar" class="form-control" id="permanent_address" value="{{old('permanent_address')}}" >
                    
                    @error('permanent_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="designation" class="form-label">Designation</label>
                    <input name="designation" type="text" class="form-control" id="designation" value="{{old('designation')}}" >
                    
                    @error('designation')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="educational_qualification" class="form-label">Educational Qualification</label>
                    <input name="educational_qualification" type="text" class="form-control" id="educational_qualification" value="{{old('educational_qualification')}}" >
                    
                    @error('educational_qualification')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="joining_date" class="form-label">Joining Date</label>
                    <input name="joining_date" type="date" class="form-control" id="joining_date" value="{{old('joining_date')}}" >
                    
                    @error('joining_date')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
                   
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/teacher-crud/edit.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">{{ $teacher->name }}</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">teachers</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Edit Teacher information
                                <a class="btn btn-sm btn-primary" href="{{ route('teachers.index')}}"> Teacher List</a>
                            </div>
                            <div class="card-body">

   @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('teachers.update', ['teacher' => $teacher->id])}}" method="POST">
    @csrf
      @method('PATCH')          

                <div class="mb-3">
                    <label for="title" class="form-label">Subject</label>
                    <input name="subject" type="text" class="form-control" id="subject" value="{{old('subject', $teacher->subject)}}">
                    
                    @error('subject')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>


                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input name="name" type="text" class="form-control" id="name" value="{{old('name', $teacher->name)}}" >
                    
                    @error('name')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="contact" class="form-label">Contact</label>
                    <input name="contact" type="number" class="form-control" id="contact" value="{{old('number', $teacher->contact)}}" >
                    
                    @error('contact')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="email" value="{{old('email', $teacher->email)}}" >
                    
                    @error('email')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="present_address" class="form-label">Present Address</label>
                    <input name="present_address" type="varchar" class="form-control" id="present_address" value="{{old('present_address', $teacher->present_address)}}" >
                    
                    @error('present_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="permanent_address" class="form-label">Permanent Address </label>
                    <input name="permanent_address" type="varchar" class="form-control" id="permanent_address" value="{{old('permanent_address', $teacher->permanent_address)}}" >
                    
                    @error('permanent_address')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="designation" class="form-label">Designation</label>
                    <input name="designation" type="text" class="form-control" id="designation" value="{{old('designation', $teacher->designation)}}" >
                    
                    @error('designation')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="educational_qualification" class="form-label">Educational Qualification</label>
                    <input name="educational_qualification" type="text" class="form-control" id="educational_qualification" value="{{old('educational_qualification', $teacher->educational_qualification)}}" >
                    
                    @error('educational_qualification')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label for="joining_date" class="form-label">Joining Date</label>
                    <input name="joining_date" type="date" class="form-control" id="joining_date" value="{{old('joining_date', $teacher->joining_date)}}" >
                    
                    @error('joining_date')
                    <div  class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
  
                <button type="submit" class="btn btn-primary">Save</button>
</form>
                            </div>
                        </div>
                   
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/teacher-crud/index.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Teachers</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item">Teachers</li>
                            <li class="breadcrumb-item active">teachers</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Teacher List
                                <a class="btn btn-sm btn-primary" href="{{ route('teachers.create')}}">Register New Teacher </a>
                            </div>
                            <div class="card-body">
                                @if(session('message'))
                                <p class="alert alert-success">{{ session('message') }}</p>
                                @endif
                                <table id="datatablesSimple" style="width : 100%">
                                    <thead>
                                        <tr>
                                            <th scope="col">ID</th>
                                            <th>Subject</th>
                                            <th>Name</th>
                                            <th>Contact </th>
                                            <th>Email</th>
                                            <th>Designation</th>
                                            <th>Action</th>
                                          
                                        </tr>
                                    </thead>
                                    
    <tbody>
        @foreach ($teachers as $teacher)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $teacher->subject }}</td>
            <td>{{ $teacher->name }} </td>
            <td>{{ $teacher->contact }} </td>
            <td>{{ $teacher->email }} </td>
            <!-- <td>{{ $teacher->present_address }} </td>
            <td>{{ $teacher->permanent_address }} </td> -->
            <td>{{ $teacher->designation }} </td>
            <!-- <td>{{ $teacher->educational_qualification }} </td>
            <td>{{ $teacher->joining_date }} </td> -->
            <td>
            <a class="btn btn-warning btn-sm" href="{{route('teachers.show', ['teacher' => $teacher->id]) }}"> Show </a>
                
                <a class="btn btn-warning btn-sm" href="{{route('teachers.edit', ['teacher' => $teacher->id]) }}"> Edit </a>
                
                <form action="{{ route('teachers.destroy', ['teacher' => $teacher->id]) }}" method="POST" style="display:inline">
                   @csrf
                   @method('delete') 
                   <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete?')">Delete</button>
                </form>
               
            
            </td>
            
        </tr>
        @endforeach
    </tbody>
</table>
                            </div>
                        </div>
                    </div>
</x-backend.admin.layouts.master>

gwp/resources/views/backend/admin/teacher-crud/show.blade.php
<x-backend.admin.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Teachers</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Teachers</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Teacher Details
                                <a class="btn btn-sm btn-primary" href="{{ route('teachers.index')}}">Teacher List </a>
                            </div>
                            <div class="card-body">

                               
                               <h3> Name: {{$teacher->name}}</h3>
                               <p> Subject: {{$teacher->subject}}</p>
                                <p> Contact: {{ $teacher->contact }} </p>
                               <p> Email: {{ $teacher->email }} </p>
                               <p> Present Address: {{ $teacher->present_address }} </p>
                               <p> Permanent Address: {{ $teacher->permanent_address }} </p>
                               <p> Designation: {{ $teacher->designation }} </p>
                               <p> Educational Qualification: {{ $teacher->educational_qualification }} </p>
                               <p> Joining Date: {{ $teacher->joining_date }} </p>
                              
                            </div>
                        </div>
                    </div>
</x-backend.admin.layouts.master>