gwp/routes/web.php
<?php

use App\Http\Controllers\DealController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [FrontendController::class, 'index'])->name('welcome');
Route::get('/', [FrontendController::class, 'home'])->name('home');
Route::get('/register-form', [FrontendController::class, 'studentpdf'])->name('student.pdf');
Route::get('/employment-form', [FrontendController::class, 'teacherpdf'])->name('teacher.pdf');





Route::get('/dashboard/admin', function () {
    return view('backend.admin.index');
})->middleware(['auth'])->name('dashboard.admin');

    Route::resource('teachers', TeacherController::class);
    Route::resource('staffs', StaffController::class);
    Route::resource('schedules', ScheduleController::class);

Route::get('/dashboard/principal', function () {
    return view('backend.principal.index');
})->middleware(['auth'])->name('dashboard.principal');

    Route::resource('deals', DealController::class);
    Route::get('/dashboard/principal/schedule', [PrincipalController::class, 'schedule'])->name('principal.schedule');




Route::get('/dashboard/parent', function () {
    return view('backend.parent.index');
})->middleware(['auth'])->name('dashboard.parent');



Route::get('/dashboard/teacher', function () {
    return view('backend.teacher.index');
})->middleware(['auth'])->name('dashboard.teacher');

    Route::resource('teachers', TeacherController::class);
    Route::get('/dashboard/teacher/schedule', [TeacherController::class, 'schedule'])->name('teacher.schedule');
    Route::get('/dashboard/teacher/croutine', [TeacherController::class, 'routine'])->name('teachers.routine');


Route::get('/dashboard/student', function () {
    return view('backend.student.index');
})->middleware(['auth'])->name('dashboard.student');

    Route::resource('students', StudentController::class);
    Route::get('/dashboard/student/schedule', [StudentController::class, 'schedule'])->name('student.schedule');
    Route::get('/dashboard/student/croutine', [StudentController::class, 'routine'])->name('students.routine');

require __DIR__.'/auth.php';

gwp/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable =[

        'student_name',
        'student_class',
        'email',
        'password',
        'father_name',
        'mother_name',
        'father_phone',
        'mother_phone',
        'date_of_birth',
        'gender',
        'adress',
    ];

    
}

gwp/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Schedule;
use App\Models\Student;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::orderBy('id','desc')->get();
        
        return view('backend.student.crud.index',compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.student.crud.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=$request->all();
       
        try 
        {
            Student::create(
                [
                'student_name'=>$data['student_name'],
                'student_class'=>$data['student_class'],
                'email'=>$data['email'],
                'password'=>$data['password'],
                'father_name'=>$data['father_name'],
                'father_phone'=>$data['father_phone'],
                'mother_name'=>$data['mother_name'],
                'mother_phone'=>$data['mother_phone'],
                'date_of_birth'=>$data['date_of_birth'],
                'gender'=>$data['gender'],
                'address'=>$data['address']
                ]);

                return redirect()->route('students.index')->withMessage('Successfully Saved !');

        } catch (QueryException $e)
        {
            // dd($ex);
        }
    
       
            // dd($request);

            return redirect()->route('backend.student.crud.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        return view('backend.student.crud.show',compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('backend.student.crud.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $data=$request->all();

        $student->update([

            'student_name'=>$data['student_name'],
              'student_class'=>$data['student_class'],
              'email'=>$data['email'],
              'password'=>$data['password'],
              'father_name'=>$data['father_name'],
              'father_phone'=>$data['father_phone'],
               'mother_name'=>$data['mother_name'],
              'mother_phone'=>$data['mother_phone'],
              'date_of_birth'=>$data['date_of_birth'],
              'gender'=>$data['gender'],
                'address'=>$data['address']

        ]);
        return redirect()->route('students.index')->withMessage('Successfully Update!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();
        return redirect()->route('students.index')->withMessage('Successfully Deleted !');
    }

    public function schedule()
    {
        $schedules = Schedule::all();
        return view('backend.student.schedule', compact('schedules'));
    }

    public function routine()
    {
        return view('backend.student.croutine');
    }
}

gwp/resources/views/backend/student/croutine.blade.php
<x-backend.student.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Class Routine</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Class Routine</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Class
                            </div>
                            <div class="card-body">
                                @if(session('message'))
                                <p class="alert alert-success">{{ session('message') }}</p>
                                @endif
                                <div class="col-md-12">
                                <table id="datatablesSimple" style="width: 100%">
                                    <thead>
                                        <tr>
                                            <th>Day</th>
                                            <th>Class 1</th>
                                            <th>Class 2</th>
                                            <th>Class 3</th>
                                            <th>Class 4</th>
                                            <th>Class 5</th>
                                            <th>Class 6</th>
                                            <th>Class 7</th>
                                        </tr>
                                    </thead>
                                    
                                    <tbody>
                                        <tr>
                                            <td>{{ 'Sunday' }} </td>
                                            <td>{{ 'English' }} </td>
                                            <td>{{ 'Bengali' }} </td>
                                            <td>{{ 'Maths' }} </td>
                                            <td>{{ 'Physics' }} </td>
                                            <td>{{ 'Chemistry' }} </td>
                                            <td>{{ 'Biology' }} </td>
                                            <td>{{ 'Pure Maths' }} </td>    
                                        </tr>

                                        <tr>
                                            <td>{{ 'Monday' }} </td>
                                            <td>{{ 'English' }} </td>
                                            <td>{{ 'Bengali' }} </td>
                                            <td>{{ 'Maths' }} </td>
                                            <td>{{ 'Physics' }} </td>
                                            <td>{{ 'Chemistry' }} </td>
                                            <td>{{ 'Biology' }} </td>
                                            <td>{{ 'Pure Maths' }} </td>    
                                        </tr>

                                        <tr>
                                            <td>{{ 'Tuesday' }} </td>
                                            <td>{{ 'English' }} </td>
                                            <td>{{ 'Bengali' }} </td>
                                            <td>{{ 'Maths' }} </td>
                                            <td>{{ 'Physics' }} </td>
                                            <td>{{ 'Chemistry' }} </td>
                                            <td>{{ 'Biology' }} </td>
                                            <td>{{ 'Pure Maths' }} </td>    
                                        </tr>

                                        <tr>
                                            <td>{{ 'Wednesday' }} </td>
                                            <td>{{ 'English' }} </td>
                                            <td>{{ 'Bengali' }} </td>
                                            <td>{{ 'Maths' }} </td>
                                            <td>{{ 'Physics' }} </td>
                                            <td>{{ 'Chemistry' }} </td>
                                            <td>{{ 'Biology' }} </td>
                                            <td>{{ 'Pure Maths' }} </td>    
                                        </tr>

                                        <tr>
                                            <td>{{ 'Thursday' }} </td>
                                            <td>{{ 'English' }} </td>
                                            <td>{{ 'Bengali' }} </td>
                                            <td>{{ 'Maths' }} </td>
                                            <td>{{ 'Physics' }} </td>
                                            <td>{{ 'Chemistry' }} </td>
                                            <td>{{ 'Biology' }} </td>
                                            <td>{{ 'Pure Maths' }} </td>    
                                        </tr>
                                        
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
</x-backend.student.layouts.master>

gwp/resources/views/backend/student/index.blade.php
<x-backend.student.layouts.master>
<div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">
			    
			    <h1 class="app-page-title"><a href="{{ route('students.index') }}">Overview</a></h1>
			    
			    <div class="app-card alert alert-dismissible shadow-sm mb-4 border-left-decoration" role="alert">
				    <div class="inner">
					    <div class="app-card-body p-3 p-lg-4">
						    <h3 class="mb-3">Welcome, Student! Role : {{Auth::user()->role_id}}</h3>
						    <div class="row gx-5 gy-3">
						        <div class="col-12 col-lg-9">
							        
							        <div>School Statistics are shown below.</div>
							    </div><!--//col-->
							    
						    </div><!--//row-->
						    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					    </div><!--//app-card-body-->
					    
				    </div><!--//inner-->
			    </div><!--//app-card-->-
				    
			    <div class="row g-4 mb-4">
				    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Name</h4>
							    <div class="stats-figure">{{ Auth::user()->name }}</div>
							    <div class="stats-meta text-success">
								    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
									<path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
									</svg>  </div>
						    </div><!--//app-card-body-->
						    <a class="app-card-link-mask" href="#"></a>
					    </div><!--//app-card-->
				    </div><!--//col-->
				    
				    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">ID</h4>
							    <div class="stats-figure">1564513</div>
							    <div class="stats-meta text-success">
								    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
									<path fill-rule="evenodd" d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1z"/>
									</svg>  </div>
						    </div><!--//app-card-body-->
						    <a class="app-card-link-mask" href="#"></a>
					    </div><!--//app-card-->
				    </div><!--//col-->
				    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Class</h4>
							    <div class="stats-figure">7</div>
							    <div class="stats-meta">
								</div>
						    </div><!--//app-card-body-->
						    <a class="app-card-link-mask" href="#"></a>
					    </div><!--//app-card-->
				    </div><!--//col-->
				    <div class="col-6 col-lg-3">
					    <div class="app-card app-card-stat shadow-sm h-100">
						    <div class="app-card-body p-3 p-lg-4">
							    <h4 class="stats-type mb-1">Subjects</h4>
							    <div class="stats-figure">7</div>
							    <div class="stats-meta"></div>
						    </div><!--//app-card-body-->
						    <a class="app-card-link-mask" href="#"></a>
					    </div><!--//app-card-->
				    </div><!--//col-->
			    </div><!--//row-->
			    <div class="row g-4 mb-4">
			        <div class="col-12 col-lg-6">
				        <div class="app-card app-card-chart h-100 shadow-sm">
					        <div class="app-card-header p-3">
						        <div class="row justify-content-between align-items-center">
							        <div class="col-auto">
						                <h4 class="app-card-title">Attendance</h4>
							        </div><!--//col-->
							        <div class="col-auto">
								        <div class="card-header-action">
									        <a href="charts.html">More charts</a>
								        </div><!--//card-header-actions-->
							        </div><!--//col-->
						        </div><!--//row-->
					        </div><!--//app-card-header-->
					        <div class="app-card-body p-3 p-lg-4">
							    <div class="mb-3 d-flex">   
							        <select class="form-select form-select-sm ms-auto d-inline-flex w-auto">
									    <option value="1" selected>This week</option>
									    <option value="2">Today</option>
									    <option value="3">This Month</option>
									    <option value="3">This Year</option>
									</select>
							    </div>
						        <div class="chart-container">
				                    <canvas id="canvas-linechart" ></canvas>
						        </div>
					        </div><!--//app-card-body-->
				        </div><!--//app-card-->
			        </div><!--//col-->
			        <div class="col-12 col-lg-6">
				        <div class="app-card app-card-chart h-100 shadow-sm">
					        <div class="app-card-header p-3">
						        <div class="row justify-content-between align-items-center">
							        <div class="col-auto">
						                <h4 class="app-card-title">Marks</h4>
							        </div><!--//col-->
							        <div class="col-auto">
								        <div class="card-header-action">
									        <a href="charts.html">More charts</a>
								        </div><!--//card-header-actions-->
							        </div><!--//col-->
						        </div><!--//row-->
					        </div><!--//app-card-header-->
					        <div class="app-card-body p-3 p-lg-4">
							    <div class="mb-3 d-flex">   
							        <select class="form-select form-select-sm ms-auto d-inline-flex w-auto">
									    <option value="1" selected>This week</option>
									    <option value="2">Today</option>
									    <option value="3">This Month</option>
									    <option value="3">This Year</option>
									</select>
							    </div>
						        <div class="chart-container">
				                    <canvas id="canvas-barchart" ></canvas>
						        </div>
					        </div><!--//app-card-body-->
				        </div><!--//app-card-->
			        </div><!--//col-->
			        
			    </div><!--//row-->
			    <div class="row g-4 mb-4">
				    <div class="col-12 col-lg-6">
				        <div class="app-card app-card-progress-list h-100 shadow-sm">
					        <div class="app-card-header p-3">
						        <div class="row justify-content-between align-items-center">
							        <div class="col-auto">
						                <h4 class="app-card-title">Homework Progress</h4>
							        </div><!--//col-->
							        <div class="col-auto">
								        <div class="card-header-action">
									        <a href="#">Assignments</a>
								        </div><!--//card-header-actions-->
							        </div><!--//col-->
						        </div><!--//row-->
					        </div><!--//app-card-header-->
					        <div class="app-card-body">
							    <div class="item p-3">
								    <div class="row align-items-center">
									    <div class="col">
										    <div class="title mb-1 ">Chemistry - Electrolysis HW</div>
										    <div class="progress">
											<div class="progress-bar bg-success" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
									    </div><!--//col-->
									    <div class="col-auto">
										    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
											</svg>
									    </div><!--//col-->
								    </div><!--//row-->
								    <a class="item-link-mask" href="#"></a>
							    </div><!--//item-->
							    
							    
							     <div class="item p-3">
								    <div class="row align-items-center">
									    <div class="col">
										    <div class="title mb-1 ">Web development of CSE Club.</div>
										    <div class="progress">
											<div class="progress-bar bg-success" role="progressbar" style="width: 34%;" aria-valuenow="34" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
									    </div><!--//col-->
									    <div class="col-auto">
										    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
											</svg>
									    </div><!--//col-->
								    </div><!--//row-->
								    <a class="item-link-mask" href="#"></a>
							    </div><!--//item-->
							    
							    <div class="item p-3">
								    <div class="row align-items-center">
									    <div class="col">
										    <div class="title mb-1 ">Business Letter Writing.</div>
										    <div class="progress">
											<div class="progress-bar bg-success" role="progressbar" style="width: 68%;" aria-valuenow="68" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
									    </div><!--//col-->
									    <div class="col-auto">
										    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
											</svg>
									    </div><!--//col-->
								    </div><!--//row-->
								    <a class="item-link-mask" href="#"></a>
							    </div><!--//item-->
							    
							    <div class="item p-3">
								    <div class="row align-items-center">
									    <div class="col">
										    <div class="title mb-1 ">Physics - Kinematics.</div>
										    <div class="progress">
											<div class="progress-bar bg-success" role="progressbar" style="width: 10%;" aria-valuenow="52" aria-valuemin="0" aria-valuemax="100"></div>
											</div>
									    </div><!--//col-->
									    <div class="col-auto">
										    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
											<path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
											</svg>
									    </div><!--//col-->
								    </div><!--//row-->
								    <a class="item-link-mask" href="#"></a>
							    </div><!--//item-->
		
					        </div><!--//app-card-body-->
				        </div><!--//app-card-->
			        </div><!--//col-->
			        <div class="col-12 col-lg-6">
				        <div class="app-card app-card-stats-table h-100 shadow-sm">
					        <div class="app-card-header p-3">
						        <div class="row justify-content-between align-items-center">
							        <div class="col-auto">
						                <h4 class="app-card-title">Subject Stats</h4>
							        </div><!--//col-->
							        <div class="col-auto">
								        <div class="card-header-action">
									        <a href="#">View report</a>
								        </div><!--//card-header-actions-->
							        </div><!--//col-->
						        </div><!--//row-->
					        </div><!--//app-card-header-->
					        <div class="app-card-body p-3 p-lg-4">
						        <div class="table-responsive">
							        <table class="table table-borderless mb-0">
										<thead>
											<tr>
												<th class="meta">Subjects</th>
												<th class="meta stat-cell">Average Marks</th>
												<th class="meta stat-cell">Today's Score</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td><a href="#">English</a></td>
												<td class="stat-cell">73</td>
												<td class="stat-cell">84</td>
											</tr>
											<tr>
												<td><a href="#">Bengali</a></td>
												<td class="stat-cell">67</td>
												<td class="stat-cell">55</td>
											</tr>
											<tr>
												<td><a href="#">Maths</a></td>
												<td class="stat-cell">84</td>
												<td class="stat-cell">90</td>
											</tr>
											<tr>
												<td><a href="#">Pure Maths</a></td>
												<td class="stat-cell">90</td>
												<td class="stat-cell">85</td>
											</tr>
											<tr>
												<td><a href="#">Physics</a></td>
												<td class="stat-cell">80</td>
												<td class="stat-cell">76</td>
											</tr>
											<tr>
												<td><a href="#">Chemistry</a></td>
												<td class="stat-cell">65</td>
												<td class="stat-cell">50</td>
											</tr>
											<tr>
												<td><a href="#">Biology</a></td>
												<td class="stat-cell">70</td>
												<td class="stat-cell">49</td>
											</tr>
										</tbody>
									</table>
						        </div><!--//table-responsive-->
					        </div><!--//app-card-body-->
				        </div><!--//app-card-->
			        </div><!--//col-->
			    </div><!--//row-->
			    
			    
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
</x-backend.student.layouts.master>

gwp/resources/views/backend/student/schedule.blade.php
<x-backend.student.layouts.master>
<div class="container-fluid px-4">
                        <h1 class="mt-4">Schedule</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                            <li class="breadcrumb-item active">Schedule</li>
                        </ol>
                        
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Events
                                <a class="btn btn-sm btn-primary" href="{{ route('schedules.create')}}">Register New Event </a>
                            </div>
                            <div class="card-body">
                                @if(session('message'))
                                <p class="alert alert-success">{{ session('message') }}</p>
                                @endif
                                <div class="col-md-12">
                                <table id="datatablesSimple" style="width: 100%">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Date</th>
                                            <th>Day</th>
                                            <th>Event</th>
                                          
                                        </tr>
                                    </thead>
                                    
                                    <tbody>
                                        @foreach ($schedules as $schedule)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $schedule->date }} </td>
                                            <td>{{ $schedule->day }} </td>
                                            <td>{{ $schedule->event }} </td>
                                            
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                                </div>
                            </div>
                        </div>
                    </div>
</x-backend.student.layouts.master>